# Generated by Django 4.0.3 on 2023-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sju', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
